### PR TITLE
Fix for bug when attempting to Cursor Slice an empty result set

### LINKED ISSUE #8: Bug in IEnumerableOffsetPagingCustomExtensions.SliceAsOffsetPage
Hi. There is a bug in this line where Take() is retrieving 1 item more than it should:

https://github.com/cajuncoding/GraphQL.RepoDB/blob/52dabefdeec5f6d29e4f97c3a927bc05426ac31c/GraphQL.PreProcessingExtensions/Paging/OffsetPaging/IEnumerableOffsetPagingCustomExtensions.cs#L54

It should be:

` var pagedResults = items.Skip(skipPast).Take(takeSome).ToList(); `

This is particular nasty if no `skip` and `take` arguments are specified in the graphql query. In that case the value for `take` will be `int.MaxValue = 2147483647`. Adding 1 to that will cause it to wrap around to `-int.MaxValue-1 = -2147483648`. This causes it to always return an empty `pagedResults`.

Rather than relying on `int.MaxValue` I think it is better to instead use the default values set when calling `IRequestExecutorBuilder.SetPagingOptions` - however I'm not sure how to inject/access these values such that `GetOffsetPagingArgsSafely` can use them:

https://github.com/cajuncoding/GraphQL.RepoDB/blob/52dabefdeec5f6d29e4f97c3a927bc05426ac31c/GraphQL.PreProcessingExtensions/Paging/OffsetPaging/IResolverContextOffsetPagingExtensions.cs#L20

I didn't specific any pagination arguments on my query and I expected it to return a page size that I set as the default. I was puzzled why I kept getting back no results.

### PR DESCRIPTION
**Pull request by davidjamesb**
When no results are returned by an underlying data source (e.g. empty list/table, etc) **IEnumerableCursorPagingCustomExtensions.SliceAsCursorPage()** creates a new **CursorPageSlice<T>** and passes null for the **results** parameter. This causes an **ArgumentException** to be thrown by the CursorPageSlice constructor. 

This bug was discovered when testing a resolver over a postgresql table I had just created but contained no rows.
The GraphQL query should return an empty node collection and totalCount = 0.

Relevant line for the bug:

https://github.com/cajuncoding/GraphQL.RepoDB/blob/52dabefdeec5f6d29e4f97c3a927bc05426ac31c/GraphQL.PreProcessingExtensions/Paging/CursorPaging/IEnumerableCursorPagingCustomExtensions.cs#L45

This can be reproduced by modifying **Tests.StarWarsCharacterResolver.CreateCharacters** to return an empty list and running the **TestParamsContextCursorPagingOnlyFirst** test.

This PR modifies behavior this by:

- Avoid throwing ArgumentException in CursorPageSlice<T> to match the way Offset pagination handles empty results.
- Swapped from creating a new List<T> to Enumerable.Empty<T>() to avoid un-needed allocation.

### CODE REVIEW

**Comment by cajuncoding** [comment]
Thanks for the details, I’ll take a look at the info provided this week!

The PR for the proposed fix is most appreciated!

File: GraphQL.PreProcessingExtensions/Paging/CursorPaging/CursorPageSlice.cs [hunk 1]
```diff
@@ -15,7 +15,7 @@ public class CursorPageSlice<TEntity> : ICursorPageSlice<TEntity>
     {
         public CursorPageSlice(IEnumerable<ICursorResult<TEntity>> results, int? totalCount, bool hasPreviousPage, bool hasNextPage)
         {
-            this.CursorResults = (results ?? throw new ArgumentException(nameof(results))).ToList();
+            this.CursorResults = results ?? Enumerable.Empty<ICursorResult<TEntity>>();
```
Comment (cajuncoding) [inline GraphQL.PreProcessingExtensions/Paging/CursorPaging/CursorPageSlice.cs]: This change will make this inconsistent with `OffsetPageResults` whereby both constructors validate that a results enumerable must be specified.  Though the `.ToList()` here does look unnecessary... I'll validate locally and remove it.

But the following changes to the Custom Extensions look to be good fixes so that they are null safe 👍

```suggestion
            this.CursorResults = results ?? throw new ArgumentException(nameof(results));
```

File: GraphQL.PreProcessingExtensions/Paging/CursorPaging/IEnumerableCursorPagingCustomExtensions.cs [hunk 2]
```diff
@@ -42,7 +42,7 @@ public static ICursorPageSlice<T> SliceAsCursorPage<T>(this IEnumerable<T> items
         {
             //Do nothing if there are no results...
             if (!items.Any())
-                return new CursorPageSlice<T>(null, 0, false, false);
+                return new CursorPageSlice<T>(Enumerable.Empty<ICursorResult<T>>(), 0, false, false);
```
Comment (cajuncoding) [inline GraphQL.PreProcessingExtensions/Paging/CursorPaging/IEnumerableCursorPagingCustomExtensions.cs:45]: Yep, nice catch and good fix to be null safe 👍

File: GraphQL.PreProcessingExtensions/Paging/OffsetPaging/IEnumerableOffsetPagingCustomExtensions.cs [hunk 3]
```diff
@@ -44,7 +44,7 @@ public static IOffsetPageResults<T> SliceAsOffsetPage<T>(this IEnumerable<T> ite
         {
             //Do nothing if there are no results...
             if (!items.Any())
-                return new OffsetPageResults<T>(new List<T>(), false, false, 0);
+                return new OffsetPageResults<T>(Enumerable.Empty<T>(), false, false, 0);
```
Comment (cajuncoding) [inline GraphQL.PreProcessingExtensions/Paging/OffsetPaging/IEnumerableOffsetPagingCustomExtensions.cs:47]: Good call, small optimization 👍

**Review by cajuncoding — CHANGES_REQUESTED** [review]
You're welcome to tweak the PR... or let me know and I'll go ahead and make these changes but thanks for the PR as this was easy to review!

Either way this is a good fix...

File: GraphQL.PreProcessingExtensions/Paging/CursorPaging/CursorPageSlice.cs (hunk 1 above)
Comment (davidjamesb) [reply GraphQL.PreProcessingExtensions/Paging/CursorPaging/CursorPageSlice.cs]: Sure thing - let's have the null check 👍

File: GraphQL.PreProcessingExtensions/Paging/CursorPaging/CursorPageSlice.cs [hunk 4]
```diff
@@ -15,7 +15,7 @@ public class CursorPageSlice<TEntity> : ICursorPageSlice<TEntity>
     {
         public CursorPageSlice(IEnumerable<ICursorResult<TEntity>> results, int? totalCount, bool hasPreviousPage, bool hasNextPage)
         {
-            this.CursorResults = (results ?? throw new ArgumentException(nameof(results))).ToList();
+            this.CursorResults = results ?? throw new ArgumentException(nameof(results));
```
Comment (cajuncoding) [inline GraphQL.PreProcessingExtensions/Paging/CursorPaging/CursorPageSlice.cs:18]: Thanks 👍

**Review by cajuncoding — APPROVED** [review]
Ok, these are good... 

And I've incorporated query Unit Tests ([here ](https://github.com/cajuncoding/GraphQL.RepoDB/blob/8edf6e755fb10ddcde83a14bd08eb0117dbd6e82/GraphQL.PreProcessingExtensions.Tests/UnitTests/ParamsContextPagingTests.cs#L56)& [here](https://github.com/cajuncoding/GraphQL.RepoDB/blob/8edf6e755fb10ddcde83a14bd08eb0117dbd6e82/GraphQL.PreProcessingExtensions.Tests/UnitTests/ParamsContextPagingTests.cs#L159)) to cover both of these use cases now in the Main branch which will validate these changes 👍

**Comment by cajuncoding** [comment]
Ok, Merged, pulled, and re-ran tests . . .  new test coverage is passing as expected (was definitely failing before).

This now resolves issue #8 👍!

image


I'll push a minor update to Nuget soon!
